services:
  java-maven-app:
    image: ndorjee/myapp:2.0
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: my-pwd


